name: The Reluctant Wedding Photographer
favicon: null
layout_spectrum: 0.49749
typography_spectrum: 0.82053
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#848484'
    - '#5e5e5e'
    - '#2a2a2a'
    - '#adadad'
    - '#d1d1d1'
  brandStrength: 0
  lightness: 0.4624077857006341
  saturation: 0.3295613257214427
  rhythmicContrast: 0.08187424694187939
purpose: []
