name: The Reluctant Wedding Photographer
favicon: null
layout_spectrum: 0.5958488336764276
typography_spectrum: 0.143912275088951
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.782618066528812
  lightness: 0.4624077857006341
  saturation: 0.3295613257214427
  rhythmicContrast: 0.08187424694187939
purpose: []
